apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-images
spec:
  images:
  - glob: "**"
  authorities:
  - name: authority-0
    key:
      hashAlgorithm: sha256
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4RXa3ulM3byejhKFxjb/OyW8OdV9
        y2VZKrbWp5plsZPza1JSPiV8rgSXR5oChqj+2MrSIf05iqgxvlFDzO/96Q==
        -----END PUBLIC KEY-----

  mode: enforce
